import assert from "node:assert/strict";
import { prisma } from "../lib/prisma.js";
import { config } from "../config.js";
import type { Prisma } from "../generated/prisma/client.js";
import { ConsentReleaseService } from "../services/consentReleases.js";
import { GoogleAuthService, googleCompleteSchema } from "../services/googleAuth.js";
import { IdentityProfileService } from "../services/identityProfile.js";

const url = new URL(config.databaseUrl);
assert(url.hostname === "127.0.0.1" && url.port !== "3306" && /^masari_auth_rehearsal_[a-z0-9_]+$/.test(url.pathname.slice(1)), "disposable_local_database_required");
assert(config.isLocal, "local_environment_required");
async function main() {
  const admin = await prisma.user.create({ data: { name: "TEST ONLY Legal Publisher", email: "legal@example.invalid", role: "admin", phone: null } });
  const legal = new ConsentReleaseService(prisma);
  const documents = (["terms", "privacy", "adult_self_attestation"] as const).flatMap(type => (["ar", "en"] as const).map(locale => ({ type, locale, content: `TEST ONLY NOT LEGAL CONTENT ${type} ${locale}` })));
  const draft = await legal.create({ version: "auth-rehearsal", intendedEffectiveAt: new Date(Date.now() - 60000), documents }, admin.id);
  const approved = await legal.approve(draft.version, draft.revision, admin.id);
  const effective = await legal.activate(draft.version, approved.revision, null, admin.id);
  const identity = { sub: "runtime-google-sub", email: "passenger@example.invalid", emailVerified: true as const };
  const google = new GoogleAuthService(prisma, config, async () => identity, legal);
  const first = await google.start("test-boundary-proof");
  const second = await google.start("test-boundary-proof");
  assert(first.kind === "registration" && second.kind === "registration");
  assert.equal(await prisma.user.count({ where: { email: identity.email } }), 0, "no_pre_consent_account");
  const complete = (grant: { registration_token: string }) => googleCompleteSchema.parse({ registration_token: grant.registration_token, name: "TEST ONLY Passenger", locale: "en", adult_self_attestation: true, consents: effective.documents.filter(d => d.locale === "en").map(d => ({ id: d.id, type: d.document_type, content_hash: d.content_digest })) });
  const createSession = (tx: Prisma.TransactionClient, user: { id: string; security_version: number }) => tx.authSession.create({ data: { user_id: user.id, client_type: "mobile", expires_at: new Date(Date.now() + 600000), security_version_at_issue: user.security_version } });
  const race = await Promise.allSettled([google.complete(complete(first), createSession), google.complete(complete(second), createSession)]);
  assert.equal(race.filter(r => r.status === "fulfilled").length, 1, "one_concurrent_registration_winner");
  assert.equal(race.filter(r => r.status === "rejected").length, 1);
  const user = await prisma.user.findUniqueOrThrow({ where: { email: identity.email } });
  assert.equal(user.role, "passenger"); assert.equal(user.profile_state, "phone_required"); assert.equal(user.phone, null);
  assert.equal(await prisma.externalIdentity.count({ where: { user_id: user.id } }), 1);
  assert.equal(await prisma.userConsent.count({ where: { user_id: user.id } }), 3);
  assert.equal(await prisma.authSession.count({ where: { user_id: user.id } }), 1);
  await assert.rejects(prisma.externalIdentity.create({ data: { user_id: admin.id, provider: "google", provider_subject: identity.sub } }), "provider_subject_uniqueness");
  await assert.rejects(prisma.externalIdentity.create({ data: { user_id: user.id, provider: "google", provider_subject: "different-sub" } }), "user_provider_uniqueness");
  let deliveredCode = "";
  const profile = new IdentityProfileService(prisma, config, undefined, { kind: "test", async send(message) { deliveredCode = message.code; } });
  const proof = await profile.phoneStart(user.id, user.security_version, { phone: "+12025550124", locale: "en" });
  assert.equal((await prisma.user.findUniqueOrThrow({ where: { id: user.id } })).profile_state, "phone_required");
  await profile.phoneConfirm(user.id, user.security_version, { action_token: proof.action_token, phone: "+12025550124", code: deliveredCode });
  const completed = await prisma.user.findUniqueOrThrow({ where: { id: user.id } });
  assert.equal(completed.profile_state, "complete"); assert(completed.phone_verified_at); assert.equal(completed.phone, "+12025550124");
  await assert.rejects(profile.phoneConfirm(user.id, user.security_version, { action_token: proof.action_token, phone: "+12025550124", code: deliveredCode }));
  const rollbackIdentity = { sub: "rollback-sub", email: "rollback@example.invalid", emailVerified: true as const };
  const rollbackGoogle = new GoogleAuthService(prisma, config, async () => rollbackIdentity, legal);
  const grant = await rollbackGoogle.start("test-boundary-proof"); assert(grant.kind === "registration");
  const counts = await Promise.all([prisma.user.count(), prisma.externalIdentity.count(), prisma.userConsent.count(), prisma.authSession.count(), prisma.authActionToken.count({ where: { consumed_at: { not: null } } })]);
  await assert.rejects(rollbackGoogle.complete(complete(grant), async (tx, newUser) => { await createSession(tx, newUser); throw new Error("intentional_transaction_failure"); }), /intentional_transaction_failure/);
  assert.deepEqual(await Promise.all([prisma.user.count(), prisma.externalIdentity.count(), prisma.userConsent.count(), prisma.authSession.count(), prisma.authActionToken.count({ where: { consumed_at: { not: null } } })]), counts, "no_partial_writes_after_rollback");
  await rollbackGoogle.complete(complete(grant), createSession);
  console.log("PASS real MySQL: legal publication, pre-consent grant, concurrent registration, identity uniqueness, account/identity/consent/session atomicity, phone completion/replay, rollback and grant retry");
}
main().catch(error => { console.error(error instanceof Error ? error.message : "auth_runtime_rehearsal_failed"); process.exitCode = 1; }).finally(() => prisma.$disconnect());
